#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import importlib.metadata
import os


# -- Project information -----------------------------------------------------

project = "vivarium.public_health"
author = "The vivarium developers"
copyright = "2023, Institute for Health Metrics and Evaluation"

version = importlib.metadata.version("vivarium-public-health")
release = version


# -- General configuration ------------------------------------------------

needs_sphinx = "4.0"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.doctest",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_click.ext",
    "sphinx_autodoc_typehints",
    "matplotlib.sphinxext.plot_directive",
]

templates_path = ["_templates"]
source_suffix = ".rst"
master_doc = "index"
language = "en"
exclude_patterns: list[str] = []
pygments_style = "sphinx"
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

html_theme_path = ["_theme"]
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_sidebars = {
    "**": [
        "globaltoc.html",
        "searchbox.html",
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

htmlhelp_basename = f"{project}doc"


# -- Options for LaTeX / man / texinfo output -----------------------------

latex_elements: dict[str, str] = {}
latex_documents = [
    (master_doc, f"{project}.tex", f"{project} Documentation", author, "manual"),
]
man_pages = [(master_doc, project, f"{project} Documentation", [author], 1)]
texinfo_documents = [
    (
        master_doc,
        project,
        f"{project} Documentation",
        author,
        project,
        "Components for modeling diseases, risks, and interventions with vivarium.",
        "Miscellaneous",
    ),
]


# -- Intersphinx ---------------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "tables": ("https://www.pytables.org/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "vivarium_engine": ("https://vivarium-engine.readthedocs.io/en/latest/", None),
    "vivarium_config_tree": (
        "https://vivarium-config-tree.readthedocs.io/en/latest/",
        None,
    ),
    "vivarium_artifact": ("https://vivarium-artifact.readthedocs.io/en/latest/", None),
}


# -- Autodoc configuration ------------------------------------------------

autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "undoc-members": True,
    "private-members": False,
}
autodoc_typehints = "description"


# -- nitpicky mode --------------------------------------------------------

nitpicky = True

nitpick_ignore = []
nitpick_path = os.path.join(os.path.dirname(__file__), "..", "nitpick-exceptions")
if os.path.exists(nitpick_path):
    with open(nitpick_path) as f:
        for line in f:
            if line.strip() == "" or line.startswith("#"):
                continue
            dtype, target = line.split(None, 1)
            target = target.strip()
            nitpick_ignore.append((dtype, target))
