#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import datetime
import importlib.metadata
import os
import subprocess

# -- Project information -----------------------------------------------------

project = "vivarium.cluster_tools"
author = "The vivarium developers"
copyright = f"2021, Institute for Health Metrics and Evaluation"

version = importlib.metadata.version("vivarium-cluster-tools")
release = version


# -- General configuration ------------------------------------------------

needs_sphinx = "4.0"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx_autodoc_typehints",
    "sphinx.ext.intersphinx",
    "sphinx.ext.doctest",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_click.ext",
    "matplotlib.sphinxext.plot_directive",
]

templates_path = ["_templates"]
source_suffix = ".rst"
master_doc = "index"
language = "en"
exclude_patterns: list[str] = []
pygments_style = "sphinx"
todo_include_todos = True

# Scoped suppression for sphinx-autodoc-typehints emitting noise when it can't
# resolve psutil's Linux-only forward-referenced types (scpufreq/scpustats/
# sdiskio/snetio in vipin/perf_counters.py, which guards them behind
# TYPE_CHECKING because they only exist on Linux). The annotations are correct
# via psutil's runtime attribute access; only the docs builder can't follow
# them on non-Linux hosts.
#
# Do NOT add unrelated warning categories here without first verifying the underlying
# issue — these suppressions narrowly target a known platform-specific quirk.
suppress_warnings = [
    "sphinx_autodoc_typehints.guarded_import",
    "sphinx_autodoc_typehints.forward_reference",
]


# -- Options for HTML output ----------------------------------------------

html_theme_path = ["_theme"]
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_css_files = ["style.css"]
html_sidebars = {
    "**": [
        "globaltoc.html",
        "searchbox.html",
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

htmlhelp_basename = f"{project}doc"


# -- Options for LaTeX / man / texinfo output -----------------------------

latex_elements: dict[str, str] = {}
latex_documents = [
    (master_doc, f"{project}.tex", f"{project} Documentation", author, "manual"),
]
man_pages = [(master_doc, project, f"{project} Documentation", [author], 1)]
texinfo_documents = [
    (
        master_doc,
        project,
        f"{project} Documentation",
        author,
        project,
        "A set of tools for running simulation using vivarium on cluster.",
        "Miscellaneous",
    ),
]


# -- Intersphinx ---------------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "tables": ("https://www.pytables.org/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "vivarium_engine": ("https://vivarium-engine.readthedocs.io/en/latest/", None),
    "vivarium_config_tree": (
        "https://vivarium-config-tree.readthedocs.io/en/latest/",
        None,
    ),
}


# -- Autodoc configuration ------------------------------------------------

# jobmon and jobmon_installer_ihme live on IHME's private PyPI mirror and
# aren't installable on RTD / public CI / most dev machines. Tell autodoc to
# substitute mock modules so it can still import `psimulate.cli`,
# `psimulate.runner`, and `psimulate.jobmon_config.workflow` (all of which
# have top-level `from jobmon... import ...` statements) for docstring
# extraction. No effect on cluster envs where jobmon is actually installed.
autodoc_mock_imports = ["jobmon", "jobmon_installer_ihme"]

autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "undoc-members": True,
    "private-members": False,
}
autodoc_typehints = "description"


# -- nitpicky mode --------------------------------------------------------

nitpicky = True

nitpick_ignore = []
nitpick_path = os.path.join(os.path.dirname(__file__), "..", "nitpick-exceptions")
if os.path.exists(nitpick_path):
    with open(nitpick_path) as f:
        for line in f:
            if line.strip() == "" or line.startswith("#"):
                continue
            dtype, target = line.split(None, 1)
            target = target.strip()
            nitpick_ignore.append((dtype, target))
