[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# FIXME [MIC-7017]: This is the minimal config to make profiling pip-installable on main
# during the monorepo migration window.
[project]
name = "vivarium-profiling"
version = "0.0.0"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "vivarium_dependencies[lint]",
    "vivarium_dependencies[pytest]",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["vivarium.profiling*"]

[tool.black]
line-length = 94

[tool.isort]
profile = "black"
line_length = 94
multi_line_output = 3
